### ISSUE TITLE
Creating new version failed: Application Error

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/ppm#102]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Hi, I have often encountered an error when trying to publish a package `Creating new version failed: Application error'. My observation I often encounter this error while trying to publish a few packages in a row.

On the same hand, I have first tried to now produce too many new tags, but to overwrite them. It looks like `--allow-same-version' doesn't work.

### Pulsar version

1.111.0

### Which OS does this happen on?

🪟 Windows

### OS details

win 10 x64

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

try to publish a package

### Additional Information:

![image](https://github.com/pulsar-edit/ppm/assets/29706474/2a2e49aa-8873-4af8-9e7f-91567428b2ca)

log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'c:\\ProgramData\\Pulsar\\resources\\app\\ppm\\bin\\node.exe',
1 verbose cli   'c:\\ProgramData\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'version',
1 verbose cli   '1.1.0',
1 verbose cli   '-m',
1 verbose cli   'Prepare v%s release'
1 verbose cli ]
2 info using npm@6.14.19-pulsar1-1
3 info using node@v16.0.0
4 verbose stack Error: Version not changed, might want --allow-same-version
4 verbose stack     at persistVersion (c:\ProgramData\Pulsar\resources\app\ppm\node_modules\npm\lib\version.js:98:16)
4 verbose stack     at c:\ProgramData\Pulsar\resources\app\ppm\node_modules\npm\lib\version.js:52:7
4 verbose stack     at c:\ProgramData\Pulsar\resources\app\ppm\node_modules\npm\lib\version.js:129:5
4 verbose stack     at c:\ProgramData\Pulsar\resources\app\ppm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
5 verbose cwd C:\Data\Develop\Pulsar\open-external
6 verbose Windows_NT 10.0.19045
7 verbose argv "c:\\ProgramData\\Pulsar\\resources\\app\\ppm\\bin\\node.exe" "c:\\ProgramData\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\bin\\npm-cli.js" "version" "1.1.0" "-m" "Prepare v%s release"
8 verbose node v16.0.0
9 verbose npm  v6.14.19-pulsar1-1
10 error Version not changed, might want --allow-same-version
11 verbose exit [ 1, true ]
```

**Comment by confused-Techie** [comment]
I've been doing some research into this one, and it seems a little strange.

For whatever reason the logs here are coming out blank, unfortunately meaning we are getting zero logging. At the very least I can confirm it's not an issue of authentication, since I can see from the logs the server is successfully authenticating you against GitHub.

I'll continue to research this and maybe being able to work in a more synchronous way on Discord would be beneficial into troubleshooting this in real time. Although there's a rather large refactor I'm planning to merge pretty soon here for the backend that may either fix this or provide more insight into what's gone wrong. 

As for the `--allow-same-version` I don't have much insight on, and would hope someone more familiar with the contents of this repo could shed some light.

**Comment by asiloisad** [comment]
I have caught the `Creating new version failed: Application Error` 2 minutes ago again 👍 It was the fifth publish in a row

**Comment by confused-Techie** [comment]
@asiloisad Thanks a ton for pinging this issue again after another retry.

I've looked into the logs and am still not seeing any errors reported. Tracing the codepath being taken, it seems that everything should be being logged properly, except the possibility of retrieving the version data from GitHub's APIs. Although that should be logged, it's possible it's not. But because this normally works, I don't think it's any actual issue of your package.

I think what might be best is for us to wait until [`pulsar-edit/package-backend#199`](https://github.com/pulsar-edit/package-backend/pull/199) gets merged, where some major improvements in this area should help us determine how to resolve this. Especially if we publish right after going to prod with this PR it'd be immensely helpful in testing it as well

**Comment by confused-Techie** [comment]
An update here, @asiloisad is that PR was merged a bit back, so it may be worth it try again. Sorry for the lag time here, but happy to hear if there's been any change.

**Comment by asiloisad** [comment]
In next week I will be releasing a lot of package updates and I will let you know if I run into this bug or not :)

**Comment by confused-Techie** [comment]
@asiloisad Sounds like a plan! If you do encounter an error just try to let me know before 30 days has passed along with a name of the package and if possible approximate time, thanks!

**Comment by asiloisad** [comment]
It look like the problem has been fixed. Thank you!
